'use client'

import type { ComponentType, ReactNode } from "react"
import { Info, Bot } from "lucide-react"
import { useTranslation } from "@ks/i18n/react"

/**
 * Wie „Mehr erfahren" verlinkt: die App mit `next/link` auf ihre eigene
 * Route, das Embed mit einem schlichten `<a>` auf die Instanz (M5).
 */
export interface HinweisLinkProps {
  href: string
  className?: string
  children: ReactNode
}

/**
 * Props für die KI-Info-Komponente
 */
interface AIGeneratedNoticeProps {
  /**
   * Optionale Liste von Quellen, die angezeigt werden sollen
   */
  sources?: Array<{ id: string; fileName?: string }>
  /**
   * Kompakte Variante für kleine Bereiche (ohne Quellenliste)
   */
  compact?: boolean
  /**
   * Zusätzliche CSS-Klassen
   */
  className?: string
  /** Wohin „Mehr erfahren" fuehrt — die rechtlichen Hinweise. */
  hinweisHref: string
  /** Womit verlinkt wird (App: `next/link`, Embed: `<a>` in neuem Tab). */
  Link: ComponentType<HinweisLinkProps>
}

/**
 * Zentrale Komponente zur Kennzeichnung von KI-generierten Inhalten
 *
 * Erfüllt die Transparenzpflicht gemäß EU AI Act Art. 50-53.
 * Kann überall eingebaut werden, wo KI-generierte Inhalte angezeigt werden.
 *
 * Seit M5 im Paket, weil die Buch-Ansicht des Embeds sie braucht. Ziel und
 * Link-Komponente kommen herein; die App reicht beides unter
 * `src/components/shared/ai-generated-notice.tsx` herein (neun Aufrufstellen).
 */
export function AIGeneratedNotice({ sources, compact = false, className = "", hinweisHref, Link }: AIGeneratedNoticeProps) {
  const { t } = useTranslation()
  const hasSources = sources && sources.length > 0

  if (compact) {
    // Kompakte Variante ohne Quellenliste
    return (
      <div className={`mt-3 pt-3 border-t border-border/50 ${className}`}>
        <div className="flex items-start gap-2 text-xs text-muted-foreground">
          <Info className="h-3.5 w-3.5 mt-0.5 flex-shrink-0" />
          <div className="flex-1">
            <span>{t('common.aiGenerated.contentAutoGenerated')}</span>
            {hasSources && (
              <span className="ml-1">
                {sources.length === 1
                  ? t('common.aiGenerated.basedOnSource', { count: sources.length })
                  : t('common.aiGenerated.basedOnSources', { count: sources.length })
                }
              </span>
            )}
            {" "}
            <Link href={hinweisHref} className="underline hover:text-foreground">
              {t('common.aiGenerated.learnMore')}
            </Link>
          </div>
        </div>
      </div>
    )
  }

  // Vollständige Variante mit Quellenliste
  return (
    <div className={`mt-4 pt-4 border-t border-border/50 ${className}`}>
      <div className="flex items-start gap-2 text-sm text-muted-foreground">
        <Bot className="h-4 w-4 mt-0.5 flex-shrink-0 text-primary" />
        <div className="flex-1 space-y-2">
          <div className="text-xs">
            <span>{t('common.aiGenerated.contentGenerated')}</span>
            {" "}
            <Link href={hinweisHref} className="underline hover:text-foreground ml-1">
              {t('common.aiGenerated.learnMoreAboutAI')}
            </Link>
          </div>
        </div>
      </div>
    </div>
  )
}

